=== JoelHer/mw-core/schemas/create_crushing.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "type": {
      "type": "string"
    },
    "ingredients": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "item": {
              "type": "string"
            }
          },
          "required": [
            "item"
          ]
        }
      ]
    },
    "results": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "item": {
              "type": "string"
            }
          },
          "required": [
            "item"
          ]
        },
        {
          "type": "object",
          "properties": {
            "item": {
              "type": "string"
            },
            "chance": {
              "type": "number"
            }
          },
          "required": [
            "item",
            "chance"
          ]
        }
      ]
    },
    "processingTime": {
      "type": "integer"
    }
  },
  "required": [
    "type",
    "ingredients",
    "results",
    "processingTime"
  ]
}

=== JoelHer/mw-core/src/main/resources/data/mw_core/recipes/crushing/ores/lead_ore.json
{
  "type": "create:crushing",
  "ingredients": [
    {
      "item": "thermal:lead_ore"
    }
  ],
  "results": [
    {
      "item": "create:crushed_lead_ore",
      "count": 2
    },
    {
      "item": "create:crushed_silver_ore",
      "chance": 0.1
    },
    {
      "item": "create:experience_nugget",
      "chance": 0.75
    },
    {
      "item": "minecraft:gravel",
      "chance": 0.2
    }
  ],
  "processingTime": 400
}

=== JoelHer/mw-core/src/main/resources/data/mw_core/recipes/crushing/ores/silver_ore.json
{
  "type": "create:crushing",
  "ingredients": [
    {
      "item": "thermal:silver_ore"
    }
  ],
  "results": [
    {
      "item": "create:crushed_silver_ore",
      "count": 2
    },
    {
      "item": "create:crushed_lead_ore",
      "chance": 0.1
    },
    {
      "item": "create:experience_nugget",
      "chance": 0.75
    },
    {
      "item": "minecraft:gravel",
      "chance": 0.2
    }
  ],
  "processingTime": 400
}

=== JoelHer/mw-core/src/main/resources/data/mw_core/recipes/crushing/ores/apatite_ore.json
{
    "type": "create:crushing",
    "ingredients": [
    	{
    		"item": "thermal:apatite_ore"
    	}
    ],
	"results": [
		{
			"item": "thermal:apatite",
			"count": 12
		},
		{
			"item": "thermal:apatite",
			"count": 1,
			"chance": 0.5
		},
		{
			"item": "minecraft:gravel",
			"count": 1,
			"chance": 0.2
		}
	],
	"processingTime": 300
}

=== JoelHer/mw-core/src/main/resources/data/mw_core/recipes/crushing/oil_sand.json
{
  "type": "create:crushing",
  "ingredients": [
    {
      "tag": "mw_core:oil_sands"
    }
  ],
  "results": [
    {
      "item": "thermal:tar",
      "count": 3
    },
    {
      "item": "thermal:niter_dust",
      "count": 3,
      "chance": 0.75
    },
    {
      "item": "thermal:bitumen",
      "chance": 0.5
    }
  ],
  "processingTime": 800
}

=== JoelHer/mw-core/src/main/resources/data/mw_core/recipes/crushing/ores/tin_ore.json
{
  "type": "create:crushing",
  "ingredients": [
    {
      "item": "thermal:tin_ore"
    }
  ],
  "results": [
    {
      "item": "create:crushed_tin_ore",
      "count": 2
    },
    {
      "item": "mw_core:crushed_apatite_ore",
      "chance": 0.5
    },
    {
      "item": "create:experience_nugget",
      "chance": 0.75
    },
    {
      "item": "minecraft:gravel",
      "chance": 0.2
    }
  ],
  "processingTime": 400
}

=== JoelHer/mw-core/src/main/resources/data/mw_core/recipes/crushing/ores/deepslate_emerald_ore.json
{
  "type": "create:crushing",
  "ingredients": [
    {
      "item": "minecraft:deepslate_emerald_ore"
    }
  ],
  "results": [
    {
      "item": "mw_core:crushed_emerald_ore",
      "count": 2
    },
    {
      "item": "mw_core:crushed_emerald_ore",
      "chance": 0.5
    },
    {
      "item": "create:experience_nugget",
      "chance": 0.75
    },
    {
      "item": "minecraft:cobbled_deepslate",
      "chance": 0.2
    }
  ],
  "processingTime": 350
}

=== JoelHer/mw-core/src/main/resources/data/mw_core/recipes/crushing/ores/deepslate_apatite_ore.json
{
    "type": "create:crushing",
    "ingredients": [
    	{
    		"item": "thermal:deepslate_apatite_ore"
    	}
    ],
	"results": [
		{
			"item": "thermal:apatite",
			"count": 12
		},
		{
			"item": "thermal:apatite",
			"count": 1,
			"chance": 0.5
		},
		{
			"item": "minecraft:cobbled_deepslate",
			"count": 1,
			"chance": 0.2
		}
	],
	"processingTime": 300
}

=== JoelHer/mw-core/src/main/resources/data/mw_core/recipes/crushing/cobalt_ore.json
{
  "type": "create:crushing",
  "ingredients": [
    {
      "tag": "forge:ores/cobalt"
    }
  ],
  "results": [
    {
      "item": "mw_core:crushed_cobalt_ore",
      "count": 2
    },
    {
      "item": "create:crushed_iron_ore",
      "chance": 0.1
    },
    {
      "item": "create:cinder_flour",
      "chance": 0.12
    },
    {
      "item": "create:experience_nugget",
      "chance": 0.75
    }
  ],
  "processingTime": 400
}
