=== JoelHer/mw-core/schemas/create_crushing.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "type": {
      "type": "string"
    },
    "ingredients": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "item": {
              "type": "string"
            }
          },
          "required": [
            "item"
          ]
        }
      ]
    },
    "results": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "item": {
              "type": "string"
            }
          },
          "required": [
            "item"
          ]
        },
        {
          "type": "object",
          "properties": {
            "item": {
              "type": "string"
            },
            "chance": {
              "type": "number"
            }
          },
          "required": [
            "item",
            "chance"
          ]
        }
      ]
    },
    "processingTime": {
      "type": "integer"
    }
  },
  "required": [
    "type",
    "ingredients",
    "results",
    "processingTime"
  ]
}

=== JoelHer/mw-core/src/main/resources/data/mw_core/recipes/crushing/ores/deepslate_diamond_ore.json
{
  "type": "create:crushing",
  "ingredients": [
    {
      "item": "minecraft:deepslate_diamond_ore"
    }
  ],
  "results": [
    {
      "item": "mw_core:crushed_diamond_ore",
      "count": 2
    },
    {
      "item": "mw_core:crushed_diamond_ore",
      "chance": 0.5
    },
    {
      "item": "create:experience_nugget",
      "chance": 0.75
    },
    {
      "item": "minecraft:cobbled_deepslate",
      "chance": 0.2
    }
  ],
  "processingTime": 350
}

=== JoelHer/mw-core/src/main/resources/data/mw_core/recipes/crushing/ores/nether_quartz_ore.json
{
  "type": "create:crushing",
  "ingredients": [
    {
      "item": "minecraft:nether_quartz_ore"
    }
  ],
  "results": [
    {
      "item": "mw_core:crushed_nether_quartz_ore",
      "count": 2
    },
    {
      "item": "mw_core:crushed_nether_quartz_ore",
      "chance": 0.5
    },
    {
      "item": "mw_core:crushed_sulfur_ore",
      "chance": 0.25
    },
    {
      "item": "create:experience_nugget",
      "chance": 0.75
    },
    {
      "item": "minecraft:netherrack",
      "chance": 0.2
    }
  ],
  "processingTime": 350
}

=== JoelHer/mw-core/src/main/resources/data/mw_core/recipes/crushing/raw_cobalt_block.json
{
  "type": "create:crushing",
  "ingredients": [
    {
      "item": "tconstruct:raw_cobalt_block"
    }
  ],
  "results": [
    {
      "item": "mw_core:crushed_cobalt_ore",
      "count": 9
    },
    {
      "item": "create:experience_nugget",
      "count": 9,
      "chance": 0.75
    }
  ],
  "processingTime": 400
}

=== JoelHer/mw-core/src/main/resources/data/mw_core/recipes/crushing/ores/deepslate_zinc_ore.json
{
  "type": "create:crushing",
  "ingredients": [
    {
      "item": "create:deepslate_zinc_ore"
    }
  ],
  "results": [
    {
      "item": "create:crushed_zinc_ore",
      "count": 2
    },
    {
      "item": "create:crushed_tin_ore",
      "chance": 0.1
    },
    {
      "item": "create:experience_nugget",
      "chance": 0.75
    },
    {
      "item": "minecraft:cobbled_deepslate",
      "chance": 0.2
    }
  ],
  "processingTime": 400
}

=== JoelHer/mw-core/src/main/resources/data/mw_core/recipes/crushing/drained_red_sand.json
{
  "type": "create:crushing",
  "ingredients": [
    {
      "item": "mw_core:drained_red_sand"
    }
  ],
  "results": [
    {
      "item": "minecraft:redstone",
      "count": 3,
      "chance": 0.25
    },
    {
      "item": "thermal:niter_dust",
      "count": 3,
      "chance": 0.75
    },
    {
      "item": "create:crushed_gold_ore",
      "chance": 0.5
    }
  ],
  "processingTime": 1600
}
